export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_FETCH_FAILURE = 'CATEGORIES_FETCH_FAILURE';
export const CATEGORIES_FETCH_START = 'CATEGORIES_FETCH_START';

export const PLAYLISTS_FETCH_SUCCESS = 'PLAYLISTS_FETCH_SUCCESS';
export const PLAYLISTS_FETCH_FAILURE = 'PLAYLISTS_FETCH_FAILURE';
export const PLAYLISTS_FETCH_START = 'PLAYLISTS_FETCH_START';

export const TRACKS_FETCH_SUCCESS = 'TRACKS_FETCH_SUCCESS';
export const TRACKS_FETCH_FAILURE = 'TRACKS_FETCH_FAILURE';
export const TRACKS_FETCH_START = 'TRACKS_FETCH_START';
