export const CATEGORIES_FETCH = 'CATEGORIES_FETCH';
export const CATEGORY_PLAYLISTS_FETCH = 'CATEGORY_PLAYLISTS_FETCH';
export const PLAYLIST_TRACKS_FETCH = 'PLAYLIST_TRACKS_FETCH';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';
